"""Stable failure-category labels surfaced in reports and policy output."""

from __future__ import annotations

FORMAT_FAILURE: str = "FORMAT_FAILURE"
SEMANTIC_REGRESSION: str = "SEMANTIC_REGRESSION"
TOOL_SELECTION_DRIFT: str = "TOOL_SELECTION_DRIFT"
ARGUMENT_VALUE_DRIFT: str = "ARGUMENT_VALUE_DRIFT"
TOOL_TRACE_STRUCTURE_DRIFT: str = "TOOL_TRACE_STRUCTURE_DRIFT"
REFUSAL_REGRESSION: str = "REFUSAL_REGRESSION"
LATENCY_REGRESSION: str = "LATENCY_REGRESSION"
COST_REGRESSION: str = "COST_REGRESSION"

__all__ = [
    "ARGUMENT_VALUE_DRIFT",
    "COST_REGRESSION",
    "FORMAT_FAILURE",
    "LATENCY_REGRESSION",
    "REFUSAL_REGRESSION",
    "SEMANTIC_REGRESSION",
    "TOOL_SELECTION_DRIFT",
    "TOOL_TRACE_STRUCTURE_DRIFT",
]
